# Data visualization 

```{r}
library(tidyverse)
library(sf)
```

```{r}
load("data/tidy_dat.RData")
```

```{r}
tidy_dat %>% 
  mutate(presence = intensity %in% c("LOW","MEDIUM","HIGH")) %>%  
  pivot_wider(names_from = "disease", values_from = "presence") %>% 
  rowwise() %>% 
  mutate(inoc_presence = sum(STEM_CANKER, HEAD_ROT, na.rm = T)) -> dat 
```

```{r}
dat_sf <- dat %>%   
    st_as_sf(coords = c('lon', 'lat'), 
           crs = st_crs(BSAS)) %>% 
  ungroup()
```

```{r}
dat_sf %>% arrange(-inoc_presence)
```

Find department of each coordinate

```{r}
int <- sf::st_intersects(dat_sf, BSAS)

dat_geo <- dat_sf %>% mutate(NAME_2 = as.character(BSAS$NAME_2[unlist(int)])) 
```

Calculate prevalence within year / department

```{r}
dat_geo %>% # count(nivel)
  group_by(year, NAME_2) %>% 
  summarise(prevalence = mean(inoc_presence)*100, 
            count_cases = sum(!is.na(inoc_presence))) -> sum_dat
```

```{r}
full <- left_join(BSAS, st_drop_geometry(sum_dat))
```

```{r}
BSAS %>% 
  ggplot() + 
  geom_sf(fill="white") + 
  geom_sf(data=full %>% drop_na(year),
          aes(fill=prevalence)) +
  geom_sf_text(data=full %>% drop_na(year),
          aes(label=count_cases))+
  facet_wrap("year", ncol=4) +
  scale_fill_viridis_c(direction = -1)+
  theme_void()  
  # theme(plot.background = element_rect(fill = "#EEEEEE"))
```

```{r}
ggsave(last_plot(), file = "figures/mapa_evol.png", w=6, h=5, bg="white")
```

Get department centroid 

```{r}
BSAS_cent <- st_centroid(BSAS)#  %>% st_transform(32617))

# check centroid location
ggplot() + 
  geom_sf(data = BSAS, fill = 'white') +
  geom_sf(data = BSAS_cent, color = 'red') 
```

```{r}
dat_cent <- sum_dat %>% 
  st_drop_geometry() %>% 
  left_join(BSAS_cent, by="NAME_2")
```

```{r}
dat_geo %>% 
  dplyr::mutate(lon = sf::st_coordinates(.)[,1],
                lat = sf::st_coordinates(.)[,2]) %>%
  st_drop_geometry() -> dat_geo_df 

dat_geo_df %>% 
  googlesheets4::write_sheet(sheet_retsave, sheet="dat_analysis")
```

```{r}
save(BSAS, tidy_dat, dat_geo, dat_geo_df, file="data/tidy_dat.RData")
```

Sunflower production by department

```{r}
sunflower_prod %>% 
  inner_join(BSAS %>% 
               mutate(department = 
           toupper(stringi::stri_trans_general(NAME_2, "Latin-ASCII"))), 
            by= "department")-> sunflower_prod_geo
```

```{r}
BSAS %>% 
  ggplot() + 
  geom_sf()+
  geom_sf(data=sunflower_prod_geo %>% filter(year_harvest>2012), 
          aes(geometry = geometry, fill=planting_area)) +
  # geom_sf_text(data=full %>% drop_na(year),
  #         aes(label=count_cases))+
  facet_wrap("year_harvest") +
  scale_fill_viridis_c(direction = -1)+
  theme_void()  
  # theme(plot.background = element_rect(fill = "#EEEEEE"))
```
